server:
  port: 8848

spring:
  devtools:
    restart:
      # 开启热部署（更改文件后，自动重启）
      enabled: true
      ## 设置哪些资源变动后不触发热部署，会覆盖默认的exclude内容（资源不会触发重启，但会触发实时重新加载）
      # exclude: WEB-INF/**,static/**
      ## 监控额外的路径（优先于exclude）
      # additional-paths: src/main/java
  application:
    name: smallStove-stove
  profiles:
    include: redis,mybatis-plus,datasource,mail
  servlet:
    multipart:
      enabled: true
      # 单个文件大小
      max-file-size: 2MB
      # 总上传文件大小
      max-request-size: 5MB

# 七牛云头像存储
oss:
  # 七牛云域名
  domainName: http://regz5bauo.hn-bkt.clouddn.com/
  accessKey: sE3Ek3xsCRjI2WS3_Lp1YSVGy7ZpTHIWUcziWidc
  secretKey: vjX7s_aDnWQ0gS3ZaIUaPtRXItcJ_cNsjXtAjqCO
  bucket: small-stove-vue