#网易系(126/163/yeah)邮箱配置
spring:
  mail:
    protocol: smtps
    #发送邮件服务器
    host: smtp.163.com
    #发送邮件的邮箱地址
    username: BugOS_ly@163.com
    #客户端授权码，不是邮箱密码
    password: KFYTWWFDUWMDPOAG
    port: 465
    # 默认编码
    default-encoding: utf-8